### ISSUE TITLE
Dependency package

### ISSUE THREAD

**Issue by godmq** [GuoYuefei/bard#5]
As stated in the readme, installing the dependency package should not use the following command <code> go install all-package </code>. Instead, you need to manually install the appropriate dependencies based on the prompts for compile errors. 
Now your package only needs to install one dependency package, but there may be more dependencies in the future, so you should write a makefile or other automatic download dependency script.
```go
go get -u gopkg.in/yaml.v2
```

**Comment by GuoYuefei** [comment]
The package management method of go mod has been adopted, and the ambiguity error in the README file has been changed.
```go
go mod tidy && go build server.go
```
